# libaom doesn't support building being in its root directory
CMAKE_BUILD_DIR=aom_build_${ANDROID_ABI}
rm -rf ${CMAKE_BUILD_DIR}
mkdir ${CMAKE_BUILD_DIR}
cd ${CMAKE_BUILD_DIR}

cmake .. \
 -DANDROID_PLATFORM=${ANDROID_PLATFORM} \
 -DANDROID_ABI=${ANDROID_ABI} \
 -DCMAKE_TOOLCHAIN_FILE=${SCRIPTS_DIR}/libaom/android.cmake \
 -DCMAKE_INSTALL_PREFIX=${BUILD_DIR_EXTERNAL}/${ANDROID_ABI} \
 -DCONFIG_PIC=1 \
 -DCONFIG_AV1_ENCODER=0 \
 -DCONFIG_RUNTIME_CPU_DETECT=0 \
 -DENABLE_TESTS=0 \
 -DENABLE_DOCS=0 \
 -DENABLE_TESTDATA=0 \
 -DENABLE_EXAMPLES=0 \
 -DENABLE_TOOLS=0

make -j${HOST_NPROC}
make install
